# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/class18/gaoruiyuan/vgg16/vgg16.cache/wt [current_project]
set_property parent.project_path /home/class18/gaoruiyuan/vgg16/vgg16.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/class18/gaoruiyuan/project/MatrixMulti/mmult_accel_core/solution1/impl/verilog.pcore [current_project]
set_property ip_output_repo /home/class18/gaoruiyuan/vgg16/vgg16.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/imports/new/ConvKernel.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/define.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/FC_FSM.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/imports/new/Multi.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/Net.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/conv_FSM.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/data_ram.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/dataloader.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/max.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/pool.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/weightloader.v
  /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/new/wrapper.v
}
read_ip -quiet /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

read_ip -quiet /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all /home/class18/gaoruiyuan/vgg16/vgg16.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file wrapper_utilization_synth.rpt -pb wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
